import cv2

cv_version = (cv2.__version__).split('.')

if cv_version[0] == '2':
    CAP_PROP_FRAME_WIDTH    = cv2.cv.CV_CAP_PROP_FRAME_WIDTH
    CAP_PROP_FRAME_HEIGHT   = cv2.cv.CV_CAP_PROP_FRAME_HEIGHT
    IMWRITE_JPEG_QUALITY    = cv2.cv.CV_IMWRITE_JPEG_QUALITY
    IMWRITE_PNG_COMPRESSION = cv2.cv.CV_IMWRITE_PNG_COMPRESSION
else:
    CAP_PROP_FRAME_WIDTH    = cv2.CAP_PROP_FRAME_WIDTH
    CAP_PROP_FRAME_HEIGHT   = cv2.CAP_PROP_FRAME_HEIGHT
    IMWRITE_JPEG_QUALITY    = cv2.IMWRITE_JPEG_QUALITY
    IMWRITE_PNG_COMPRESSION = cv2.IMWRITE_PNG_COMPRESSION
